# Generated by Django 4.2.2 on 2023-06-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_guest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name='Tasting Date')),
                ('time', models.CharField(choices=[('M', 'Morning Tasting'), ('A', 'Afternoon Tasting'), ('N', 'Night Tasting')], default='M', max_length=1)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='WineTasting',
        ),
        migrations.AddField(
            model_name='guest',
            name='wine',
            field=models.ManyToManyField(to='main_app.wine'),
        ),
        migrations.AddField(
            model_name='tasting',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guest'),
        ),
    ]
